name: Gerar Gr치fico de Cobrinha

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza todo dia  meia-noite (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 游닌 Clonar reposit칩rio
        uses: actions/checkout@v3

      - name: 游꿡 Gerar gr치fico estilo Pac-Man
        uses: Platane/snk@v3
        with:
          github_user_name: OtavioAugustodaRoza
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: 游 Publicar resultado na branch output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
