name: Generate Pacman Animation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Pacman Animation
        uses: yoshi389111/github-profile-3d-contrib@main
        with:
          output_path: "./output"
          theme: "pacman"
          animate: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/*
          git commit -m "Generate Pacman Animation" || echo "No changes"
          git push

