name: Generate Pacman Animation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Pacman Animation
        uses: zhangxinxu/pacman-contributions@v1
        with:
          username: "kauan1099"
          output: "output/pacman.gif"
      - name: Push generated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/pacman.gif
          git commit -m "Generate Pacman Animation" || echo "No changes"
          git push
